name: InventoryStacks
version: 2.5-BETA
api-version: 1.13
main: com.codingguru.inventorystacks.InventoryStacks
authors: [CodingGuru]
folia-supported: true
commands:
    stack:
     description: Stack all items in your inventory.
    stacks:
     description: Reload inventory stacks.
    inventorystacks:
     description: Reload inventory stacks.