name: TrailPaths
version: 1.7.1
api-version: 1.13
main: com.codingguru.trailpaths.TrailPaths
authors: [CodingGuru]
folia-supported: true
commands:
    trails:
     description: All the commands for this plugin.